name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./website
        run: npm install

      - name: Build Angular app
        working-directory: ./website
        run: npm run build -- --configuration production

      - name: Debug - Show files
        run: |
          echo "Looking for index.html:"
          find ./website/dist -name "index.html"
          echo "---"
          ls -la ./website/dist/website/browser/

      - name: Copy index.html to 404.html
        run: cp ./website/dist/website/browser/index.html ./website/dist/website/browser/404.html

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/dist/website/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4